baseURL = 'https://nicogreu.github.io/'
languageCode = 'en-us'
title = 'Nicolas Greliche'
metaDataFormat = "yaml"
theme = 'blist'


DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 0
    languageName = "English"

    [[languages.en.menu.main]]
        name = "About"
        url = "/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Research"
        url = "/research/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Consulting"
        url = "/consulting/"
        weight = 3

    [[languages.en.menu.main]]
        name = "Outreach"
        url = "/outreach/"
        weight = 4

    [[languages.en.menu.main]]
        name = "Art"
        url = "/art/"
        weight = 5

    [[languages.en.menu.main]]
        name = "CV"
        url = "/cv/"
        weight = 6

    [[languages.en.menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 7


  [languages.fr]
    contentDir = "content/fr" #French
    weight = 0
    languageName = "Francais"
    [languages.fr.params]

    [[languages.fr.menu.main]]
        name = "Bio"
        url = "/"
        weight = 1

    [[languages.fr.menu.main]]
        name = "Recherche"
        url = "/research/"
        weight = 2

    [[languages.fr.menu.main]]
        name = "Conseil"
        url = "/conseil/"
        weight = 3

    [[languages.fr.menu.main]]
        name = "Diffusion"
        url = "/outreach/"
        weight = 4

    [[languages.fr.menu.main]]
        name = "Art"
        url = "/art/"
        weight = 5

    [[languages.fr.menu.main]]
        name = "CV"
        url = "/cv/"
        weight = 6

    [[languages.fr.menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 7


[params]

  custom_css = ["/css/custom.css"]

  introPhoto = "/images/Me tweaked.jpg"

  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = false

  # Custom copyright - optional
  copyright = "Copyright © 2026 - Nicolas Greliche · All rights reserved"
  favicon = "/favicon_colored.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-white"

  # The page bundle that is shown on the front page
  frontBundle = "page"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = false

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"


  [[params.homepage.social.icons]]
    website = "PhilPeople"
    url = "https://philpeople.org/profiles/nicolas-greliche"
  [[params.homepage.social.icons]]
    website = "instagram"
    url = "https://www.instagram.com/duduqdrawstuff/"
  [[params.homepage.social.icons]]
    website = "whatsapp"
    url = "https://wa.me/33684211454"
  [[params.homepage.social.icons]]
    website = "mastodon"
    url = "https://mastodon.social/@nicogreu"
  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://linkedin.com/in/nicolas-greliche/"
  [[params.homepage.social.icons]]
    website = "googlescholar"
    url = "https://scholar.google.es/citations?user=XDIgmMMAAAAJ/"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/nicogreu/"
  [[params.homepage.social.icons]]
    website = "orcid"
    url = "https://orcid.org/0000-0003-0683-2257"
  [[params.homepage.social.icons]]
    website = "buymeacoffee"
    url = "https://www.buymeacoffee.com/nicogreu/"
  [[params.homepage.social.icons]]
    website = "twitter"
    url = "https://twitter.com/"
  [[params.homepage.social.icons]]
    website = "xing"
    url = "https://www.xing.com/profile/"
  [[params.homepage.social.icons]]
    website = "telegram"
    url = "https://t.me/"
  [[params.homepage.social.icons]]
    website = "medium"
    url = "https://medium.com/"
  [[params.homepage.social.icons]]
    website = "reddit"
    url = "https://reddit.com/"
  [[params.homepage.social.icons]]
    website = "dribbble"
    url = "https://dribbble.com/"
  [[params.homepage.social.icons]]
    website = "stackoverflow"
    url = "https://stackoverflow.com/"
  [[params.homepage.social.icons]]
    website = "xda"
    url = "https://forum.xda-developers.com/"
  [[params.homepage.social.icons]]
    website = "tiktok"
    url = "https://tiktok.com"
  [[params.homepage.social.icons]]
    website = "youtube"
    url = "https://youtube.com"
  [[params.homepage.social.icons]]
    website = "facebook"
    url = "https://facebook.com"
  [[params.homepage.social.icons]]
    website = "behance"
    url = "https://behance.net"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
  [markup.goldmark.parser]
    wrapLineLength = 0
    hardWraps = false
    autoHeadingID = true


# ======================================
# URL Settings (Permalinks)
# ======================================
# This ensures static pages (like Research, CV) have clean URLs (e.g., /research/)
# It also ensures blog posts go under /posts/
[permalinks]
page = "/:slug/"
posts = "/posts/:slug/"